### ISSUE TITLE
You Said Build Apk...

### ISSUE THREAD

**Issue by gituu4567** [blastlaboratory/Fucking-Rat#1]

**Comment by gituu4567** [comment]
> _No description provided._

But Haven't Mentioned or gave any java or other apk source file ...

**Comment by swagkarna** [comment]
If i give source file u will tear the sky....First shut your mouth and read the `READMEFILE`
I have clearly mentioned i dont need any one to open issue for this repo.U have violated my words  
and asking for help....No more help will be provided..
